# Synapse2 日志配置
# 针对生产环境和调试的日志设置

version: 1

formatters:
  precise:
    format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'
  
  chinese:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: precise
    filename: /data/logs/homeserver.log
    when: midnight
    interval: 1
    backupCount: 7
    encoding: utf8
    
  friends_file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: chinese
    filename: /data/logs/friends.log
    when: midnight
    interval: 1
    backupCount: 7
    encoding: utf8
    
  error_file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: precise
    filename: /data/logs/error.log
    when: midnight
    interval: 1
    backupCount: 30
    encoding: utf8
    level: ERROR
    
  console:
    class: logging.StreamHandler
    formatter: chinese
    stream: ext://sys.stdout
    
  # 性能监控日志
  performance_file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: chinese
    filename: /data/logs/performance.log
    when: midnight
    interval: 1
    backupCount: 7
    encoding: utf8

loggers:
  synapse:
    level: INFO
    handlers: [file, console]
    propagate: false
    
  synapse.access:
    level: INFO
    handlers: [file]
    propagate: false
    
  synapse.handlers.friends:
    level: INFO
    handlers: [friends_file, console]
    propagate: false
    
  synapse.storage.friends:
    level: INFO
    handlers: [friends_file]
    propagate: false
    
  synapse.rest.client.friends:
    level: INFO
    handlers: [friends_file]
    propagate: false
    
  synapse.performance:
    level: INFO
    handlers: [performance_file]
    propagate: false
    
  synapse.federation:
    level: WARNING
    handlers: [file]
    propagate: false
    
  synapse.http:
    level: WARNING
    handlers: [file]
    propagate: false
    
  synapse.metrics:
    level: WARNING
    handlers: [file]
    propagate: false
    
  # 第三方库日志级别
  twisted:
    level: WARNING
    handlers: [file]
    propagate: false
    
  requests:
    level: WARNING
    handlers: [file]
    propagate: false
    
  urllib3:
    level: WARNING
    handlers: [file]
    propagate: false

root:
  level: INFO
  handlers: [file, error_file]

# 禁用某些详细日志
disable_existing_loggers: false

# 日志轮转配置
log_rotation:
  max_size: 100MB
  backup_count: 10
  
# 中文日志消息配置
chinese_logging:
  enabled: true
  encoding: utf-8
  date_format: '%Y年%m月%d日 %H:%M:%S'
  
# 性能日志配置
performance_logging:
  enabled: true
  log_slow_queries: true
  slow_query_threshold: 1.0  # 秒
  log_cache_hits: false
  log_memory_usage: true
  memory_check_interval: 300  # 秒